### ISSUE TITLE
Erros pós instalção

### ISSUE THREAD

**Issue by dilJF** [marcosvpinto/estoque#1]
Boa tarde,

                Achei na internet seu projeto de Controle de Estoque e estou tentando instalar em minha máquina para ver se consigo usar para o almoxarifado interno em minha empresa.
                Criei a base de dados e baixei o código da aplicação.
                
                Estou conseguindo abrir a tela de Login, porém com alguns erros que não consegui sanar (não sou programador nato)
                
                Encaminhei anexo em seu email as telas com os erros e se vc puder me ajudar a resolver ficaria agradecido.

Att,
Adilson Almeida

**Comment by marcosvpinto** [comment]
Acerto realizado na Classe Common.php da pasta system/core com remoção de código duplicado. Ver commit para mais informações.
