### ISSUE TITLE
Erro ao executar

### ISSUE THREAD

**Issue by anevesb** [marcosvpinto/estoque#11]
Estou recebendo o seguinte erro ao tentar rodar o localhost:
Deprecated: Required parameter $message follows optional parameter $level in C:\xampp\htdocs\estoque-master\system\core\Common.php on line 351
﻿
A PHP Error was encountered
Severity: Notice

Message: Only variables should be assigned by reference

Filename: core/Loader.php

Line Number: 150

A PHP Error was encountered
Severity: 8192

Message: Required parameter $list follows optional parameter $type

Filename: helpers/html_helper.php

Line Number: 106

Fatal error: Uncaught Error: Call to undefined function mysql_pconnect() in C:\xampp\htdocs\estoque-master\system\database\drivers\mysql\mysql_driver.php:91 Stack trace: #0 C:\xampp\htdocs\estoque-master\system\database\DB_driver.php(115): CI_DB_mysql_driver->db_pconnect() #1 C:\xampp\htdocs\estoque-master\system\database\DB.php(148): CI_DB_driver->initialize() #2 C:\xampp\htdocs\estoque-master\system\core\Loader.php(346): DB(Array, NULL) #3 C:\xampp\htdocs\estoque-master\system\core\Loader.php(1171): CI_Loader->database() #4 C:\xampp\htdocs\estoque-master\system\core\Loader.php(152): CI_Loader->_ci_autoloader() #5 C:\xampp\htdocs\estoque-master\system\core\Controller.php(51): CI_Loader->initialize() #6 C:\xampp\htdocs\estoque-master\system\core\CodeIgniter.php(308): CI_Controller->__construct() #7 C:\xampp\htdocs\estoque-master\index.php(202): require_once('C:\\xampp\\htdocs...') #8 {main} thrown in C:\xampp\htdocs\estoque-master\system\database\drivers\mysql\mysql_driver.php on line 91

**Comment by marcosvpinto** [comment]
Olá amigo, pode confirmar se está utilizando o PHP na versão abaixo?

**PHP 5**
JQuery 1.9.1
MySQL 5.3
Framework Code Igniter 2 (PHP 5.1+)
Framework Boostrap v. 2.3.2 (CSS)

Esses erros indicam versão diferente, por isso o Code Igniter não consegue rodar corretamente.

**Comment by anevesb** [comment]
Olá Marcos, obrigado por responder a questão acima, modifiquei para as versões indicadas e não recebo mais aqueles erros, porém um permanece, segue abaixo:

A Database Error Occurred
Unable to connect to your database server using the provided settings.

Filename: C:\xxx\xxx\xxx\UniServerZ\www\estoque-master\estoque-master\system\database\DB_driver.php

Line Number: 124

Estou usando o uniserver, com a configuração padrão e sem senha no BD

**Comment by marcosvpinto** [comment]
Camarada, você consegue usar o MySQL ? 
Para o Uniserver, verifique o arquivo de configurações do banco de dados no Code Igniter se as configurações estão corretas, tanto de driver, quanto de portas e endereço. 
O arquivo em questão é:
estoque/application/config/database.php

**Comment by anevesb** [comment]
Desculpe, na verdade o Uniserver já veio com uma senha para o MySQL, modifiquei no arquivo database.php  e foi, muito obrigado, de verdade.

**Comment by marcosvpinto** [comment]
Excelente! 
Boa sorte e não tenha medo de perguntar em qualquer dúvida! 
Marcarei como finalizado o problema, ok?
