### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by xstocler** [marcosvpinto/estoque#2]
Estou com xampp rodando localmente na minha maquina para rodar o sistema desenvolvido.
Mas estou com dificuldades em rodar ele.
Fiz a importação do sql, quais os próximos passos?
Agradeço

**Comment by marcosvpinto** [comment]
Olá, poderia prover mais informações?
- Você criou uma database chamada controle_estoque ? Se chamou de outro nome, configurou no arquivo application/config/Database.php ?
- Configurou o usuário e senha de banco no arquivo application/config/Database.php ?
- Apresenta algum erro em tela?
- Usou o usuário admin com senha admin ?
- Passou da tela de login e apresentou algum outro erro?

**Comment by xstocler** [comment]
Então,
Criei o banco mysql em uma hospedagem free com o nome:
```
['hostname'] = 'localhost';
['username'] = 'id1461183_usersite';
['database'] = 'id1461183_bdsite';
```

Quando importo o arquivo SQL para o banco apresenta este erro:

```
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_AtualizaEstoque`(IN `id_produto` INT, IN `quantidade_in` INT, IN `opcao` CHAR(1), IN `cod_pedido` INT)
BEGIN
    DECLARE contador INT(11);
  
	CASE opcao 
		WHEN 'S'
			THEN 
				BEGIN
					DECLARE qtd_estoque INT (4);
					SELECT quantidade INTO qtd_estoque FROM estoque WHERE produto = id_produto;
					IF qtd_estoque >= (quantidade_in*-1) THEN
						UPDATE estoque SET quantidade=quantidade + quantidade_in WHERE produto = id_produto;
					ELSE 
						UPDATE estoque SET quantidade=quantidade WHERE produto = id_produto;
					END IF;
				END;

		WHEN 'N'
			THEN INSERT INTO estoque (produto) values (id_produto);
		
		WHEN 'I'
			THEN UPDATE estoque SET quantidade=quantidade + quantidade_in WHERE produto = id_produto;
		
		WHEN 'R'
			THEN UPDATE estoque SET quantidade=quantidade - quantidade_in WHERE produto = id_produto;
		ELSE 
			BEGIN 
			END;
	END CASE;
 
END
MySQL said: Documentation
#1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation

```


Tentei alterar alguns parâmetros mas mesmo assim continua dando erro ao importar

**Comment by marcosvpinto** [comment]
Olá amigo!
O erro não está no script, mas sim em como você está rodando o script que cria o banco de dados. Observe o erro que ele indica: 
`
MySQL said: Documentation
#1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation
`
Fazendo um rápido Google, verifiquei esta resposta no StackOverflow que pode te ajudar: 
[https://stackoverflow.com/questions/11946012/how-to-add-super-privileges-to-mysql-database](https://stackoverflow.com/questions/11946012/how-to-add-super-privileges-to-mysql-database)

Verifique no seu painel de controle do MySQL da sua hospedagem se você consegue fazer o descrito na resposta e rode novamente o script.

Abraços

**Comment by xstocler** [comment]
Agradeço pela resposta.
Mas não consigo fazer nenhuma ação, estou usando o banco do 000webhost.

**Comment by marcosvpinto** [comment]
Porque você não testa a aplicação no seu próprio computador? O serviço do Apache/PHP e o banco de dados MySQL requerem baixas configurações e não exigem uma máquina poderosa, na verdade, praticamente qualquer máquina consegue rodar!
Caso não tenha prática, segue um tutorial bem explicado de como instalar o ambiente XAMPP que vem com tudo o que você precisa para instalar meu sistema de estoque:  
[http://www.bosontreinamentos.com.br/php-programming/curso-de-php-instalando-o-xampp-no-windows-apache-mysql-php-e-perl/](http://www.bosontreinamentos.com.br/php-programming/curso-de-php-instalando-o-xampp-no-windows-apache-mysql-php-e-perl/)
Qualquer dúvida adicional, não exite em me contactar, podendo ser inclusive por email: mvpdev@gmail.com

Abraços

**Comment by xstocler** [comment]
Depois de alguns meses resolvi rodar o sistema no wampserver.
Fiz os seguintes passos:

- Criar a database com nome controle_estoque
- Remover a senha do mysql no arquivo application/config/Database.php (por ser wampserver)

Tentei acessar a página e está com alguns erros.
Talvez por esses erros, não loga usando admin admin.

Erro 1 
`A PHP Error was encountered
Severity: Warning
Message: strtolower() expects parameter 1 to be string, array given
Filename: helpers/form_helper.php
Line Number: 983
`

Erro 2
`A PHP Error was encountered
Severity: Notice
Message: Only variable references should be returned by reference
Filename: core/Common.php
Line Number: 257
`

Erro 3
`A PHP Error was encountered
Severity: Notice
Message: Array to string conversion
Filename: core/Common.php
Line Number: 153
`

erro 4
`A PHP Error was encountered
Severity: Notice
Message: Array to string conversion
Filename: core/Security.php
Line Number: 116
`

Agradeço
