### ISSUE TITLE
Erro na página

### ISSUE THREAD

**Issue by xstocler** [marcosvpinto/estoque#3]
Depois de alguns meses resolvi rodar o sistema no wampserver.
Fiz os seguintes passos:

- Criar a database com nome controle_estoque
- Remover a senha do mysql no arquivo application/config/Database.php (deixar em branco por ser wampserver)
- Importar o arquivo .sql

Ao acessar a página login e está com alguns erros.

Erro 1
`A PHP Error was encountered Severity: Warning Message: strtolower() expects parameter 1 to be string, array given Filename: helpers/form_helper.php Line Number: 983
`
Erro 2
`A PHP Error was encountered Severity: Notice Message: Only variable references should be returned by reference Filename: core/Common.php Line Number: 257
`
Erro 3
`A PHP Error was encountered Severity: Notice Message: Array to string conversion Filename: core/Common.php Line Number: 153
`
erro 4
`A PHP Error was encountered Severity: Notice Message: Array to string conversion Filename: core/Security.php Line Number: 116
`

Após logar usando admin/admin
Está aparecendo os erros no top da página:

`( ! ) Notice: Array to string conversion in C:\wamp64\www\vs\system\core\Common.php on line 153`

`1 | 0.0002 | 253800 | {main}( ) | ...\index.php:0
2 | 0.0007 | 311696 | require_once( 'C:\wamp64\www\vs\system\core\CodeIgniter.php' ) | ...\index.php:202
3 | 0.0013 | 379792 | load_class( ) | ...\CodeIgniter.php:115
4 | 0.0016 | 392192 | config_item( ) | ...\Common.php:153
5 | 0.0016 | 392272 | get_config( ) | ...\Common.php:277
6 | 0.0018 | 402176 | _exception_handler( ) | ...\Common.php:257
7 | 0.0018 | 402336 | load_class( ) | ...\Common.php:483`

Poderia me ajudar?

**Comment by marcosvpinto** [comment]
Olá novamente! 
Bom que conseguiu usar um servidor local, os testes ficam facilitados!

Qual a versão do Wampserver que você está usando? Se a mesma tiver o PHP7, este erro ocorrerá porque a versão do CodeIgniter que o controle de estoque usa é a 2.x e ela tem algumas incompatibilidades com o PHP7. 
Verifique se você consegue uma versão do Wampserver que rode o PHP 5.x e execute novamente o controle de estoque.

Tenho previsão de liberar uma versão atualizada do controle de estoque com o framework atualizado para a versão 3.x dentro de 1 mês.

Abraços, 
Marcos.

**Comment by xstocler** [comment]
Agradeço pelo retorno.

Estou usando a última versão do WampServer, ele está usando a versão 7 do php.

Irei baixar uma versão com php 5.x

Irei aguardar a atualização do framework.

Agradeço pelo retorno.
