### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by nandofpatezz** [marcosvpinto/estoque#6]
Gostaria de saber onde estão os arquivos que devem ser actualizados, referente a banco de dados ,etc...

**Comment by marcosvpinto** [comment]
Olá @nandofpatezz , o banco de dados está no arquivo database.sql, localizado na raiz do projeto. Esse script ao ser importado no banco de dados cria todas as tabelas necessárias ao sistema e seu primeiro usuário (admin).
Sinalize se houver mais dúvidas para que eu reabra a issue.
