### ISSUE TITLE
como instalo

### ISSUE THREAD

**Issue by sandrecardoso** [marcosvpinto/estoque#7]
não consigo rodar em localhost

**Comment by marcosvpinto** [comment]
Olá Sandré!
Você instalou a versão do PHP, Apache e MySQL indicada no README ?
Após instalar siga os passos: 
- coloque a pasta do projeto dentro da pasta de arquivos de internet (www ou htdocs);
- crie uma base de dados com o nome "controle_estoque";
- importe o arquivo "database.sql" (localizado na raiz do projeto)
- acesse o sistema e logue com o usuário admin / senha admin

**Comment by sandrecardoso** [comment]
Estou usando o easyphp vou instalar o wamp server e tentar de novo

Em sex, 24 de jul de 2020 11:50, Marcos Vinícius Pinto <
notifications@github.com> escreveu:

**Comment by isaacsaid2021** [comment]
boa tarde quando subo o arquivo database.sql da o seguinte erro : consegue me ajudar ?

Erro
Query SQL: Copiar Documentação


--
-- Procedimentos
--
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_AtualizaEstoque`(IN `id_produto` INT, IN `quantidade_in` INT, IN `opcao` CHAR(1), IN `cod_pedido` INT)
BEGIN
    DECLARE contador INT(11);
  
	CASE opcao 
		WHEN 'S'
			THEN 
				BEGIN
					DECLARE qtd_estoque INT (4);
					SELECT quantidade INTO qtd_estoque FROM estoque WHERE produto = id_produto;
					IF qtd_estoque >= (quantidade_in*-1) THEN
						UPDATE estoque SET quantidade=quantidade + quantidade_in WHERE produto = id_produto;
					ELSE 
						UPDATE estoque SET quantidade=quantidade WHERE produto = id_produto;
					END IF;
				END;

		WHEN 'N'
			THEN INSERT INTO estoque (produto) values (id_produto);
		
		WHEN 'I'
			THEN UPDATE estoque SET quantidade=quantidade + quantidade_in WHERE produto = id_produto;
		
		WHEN 'R'
			THEN UPDATE estoque SET quantidade=quantidade - quantidade_in WHERE produto = id_produto;
			
		ELSE 
			BEGIN 
			END;
	END CASE;
 
END;
Mensagem do MySQL: Documentação

#1227 - Acesso negado. Você precisa o privilégio SUPER para essa operação

**Comment by isaacsaid2021** [comment]
quando tento cadastrar uma nota fiscal da esse erro tambem : 

A Database Error Occurred
Error Number: 1305

PROCEDURE sahostco_controledeestoque.SP_AtualizaEstoque does not exist

INSERT INTO `item` (`cod_nota`, `cod_produto`, `quantidade`, `valor_item`) VALUES ('259', '110', '100', '2')

Filename: /home/sahostdemo/domains/sahost.cf/public_html/models/mitemnota.php

Line Number: 11

**Comment by marcosvpinto** [comment]
Olá Isaac, 

O erro aconteceu porque o sistema não encontrou a procedure no banco de dados. Pela mensagem que me enviou anteriormente, vi que você não tinha privilégios no banco de dados para criar uma procedure. O Script do banco de dados que está contido no sistema execute o SQL que cria a procedure, mas você precisa se certificar que seu usuário de banco tem o direito de criar procedures.

**Comment by isaacsaid2021** [comment]
bom dia tudo bem obrigado por responder estou usando um plano de hospedagem
web.. então pra rodar vou ter que montar um server local com acesso de root
para poder subir o banco correto porque criou as tabelas mesmo com os erros
acesso o sistema normal so que não consigo finalizar um pedido da um erro
de banco deve ser porque não criou a procedure ?

Em sex., 18 de jun. de 2021 às 21:07, Marcos Vinícius Pinto <
***@***.***> escreveu:

**Comment by marcosvpinto** [comment]
No caso do erro com o pedido é exatamente isso, sem a procedure, o sistema
falha.
No caso da sua hospedagem web, acredito que você possa recorrer ao suporte
para pedir um usuário com poderes administrativos no banco ou que eles
rodem a criação da procedure para você.

Em sáb, 19 de jun de 2021 11:59, isaacsaid2021 ***@***.***>
escreveu:

**Comment by isaacsaid2021** [comment]
olá bom dia tudo bem? conseguei resolver o problemas do banco agora só que
quando vou finalizar um pedido da esse erro :  Não é possível fechar um
pedido com itens em aberto.   não consigo finalizar o cadastro para fazer o
pedido. pode me ajudar ?

obrigado

Em sáb., 19 de jun. de 2021 às 12:26, Marcos Vinícius Pinto <
***@***.***> escreveu:

**Comment by marcosvpinto** [comment]
Isaac, provavelmente porque você teve pedidos gerados antes da criação da procedure, o que causou a falta de informações no banco de dados. Caso seja possível, recomendo que você zere os dados da base de dados para que os novos sejam criados corretamente.

**Comment by isaacsaid2021** [comment]
A base está zerada fiz o cadastro dos produtos do zero agora sem nenhum
erro só dá mensagem quando vou finalizar o cadastro no menu pedido diz que
o pedido está aberto rss não vai será se liberar o acesso pra vc vc
consegue me ajudar ?

Em seg, 21 de jun de 2021 15:33, Marcos Vinícius Pinto <
***@***.***> escreveu:

**Comment by isaacsaid2021** [comment]
Se vc tiver um ZAP que eu possa falar com vc fico agradecido abs

Em seg, 21 de jun de 2021 17:24, Tv Amor de Maria ***@***.***>
escreveu:

**Comment by isaacsaid2021** [comment]
boa noite marcos tudo bem consegui resolver o erro so que os botoes xls csv
pdf não estão aparecendo sabe me dizer o que possa ser ?

aguardo a imagem esta anexada.

Em sex., 18 de jun. de 2021 às 21:07, Marcos Vinícius Pinto <
***@***.***> escreveu:
